import { Colour, Type } from '../common/types';

export const pack = [
    { colour: Colour.YELLOW, type: Type.NUMBER, value: 1 },
    { colour: Colour.YELLOW, type: Type.NUMBER, value: 2 },
    { colour: Colour.YELLOW, type: Type.NUMBER, value: 3 },
    { colour: Colour.YELLOW, type: Type.NUMBER, value: 4 },
    { colour: Colour.YELLOW, type: Type.NUMBER, value: 5 },
    { colour: Colour.YELLOW, type: Type.NUMBER, value: 6 },
    { colour: Colour.YELLOW, type: Type.NUMBER, value: 7 },
    { colour: Colour.YELLOW, type: Type.NUMBER, value: 8 },
    { colour: Colour.YELLOW, type: Type.NUMBER, value: 9 },
    { colour: Colour.YELLOW, type: Type.NUMBER, value: 10 },
    { colour: Colour.YELLOW, type: Type.NUMBER, value: 11 },
    { colour: Colour.YELLOW, type: Type.NUMBER, value: 12 },
    { colour: Colour.YELLOW, type: Type.NUMBER, value: 13 },

    { colour: Colour.GREEN, type: Type.NUMBER, value: 1 },
    { colour: Colour.GREEN, type: Type.NUMBER, value: 2 },
    { colour: Colour.GREEN, type: Type.NUMBER, value: 3 },
    { colour: Colour.GREEN, type: Type.NUMBER, value: 4 },
    { colour: Colour.GREEN, type: Type.NUMBER, value: 5 },
    { colour: Colour.GREEN, type: Type.NUMBER, value: 6 },
    { colour: Colour.GREEN, type: Type.NUMBER, value: 7 },
    { colour: Colour.GREEN, type: Type.NUMBER, value: 8 },
    { colour: Colour.GREEN, type: Type.NUMBER, value: 9 },
    { colour: Colour.GREEN, type: Type.NUMBER, value: 10 },
    { colour: Colour.GREEN, type: Type.NUMBER, value: 11 },
    { colour: Colour.GREEN, type: Type.NUMBER, value: 12 },
    { colour: Colour.GREEN, type: Type.NUMBER, value: 13 },

    { colour: Colour.BLUE, type: Type.NUMBER, value: 1 },
    { colour: Colour.BLUE, type: Type.NUMBER, value: 2 },
    { colour: Colour.BLUE, type: Type.NUMBER, value: 3 },
    { colour: Colour.BLUE, type: Type.NUMBER, value: 4 },
    { colour: Colour.BLUE, type: Type.NUMBER, value: 5 },
    { colour: Colour.BLUE, type: Type.NUMBER, value: 6 },
    { colour: Colour.BLUE, type: Type.NUMBER, value: 7 },
    { colour: Colour.BLUE, type: Type.NUMBER, value: 8 },
    { colour: Colour.BLUE, type: Type.NUMBER, value: 9 },
    { colour: Colour.BLUE, type: Type.NUMBER, value: 10 },
    { colour: Colour.BLUE, type: Type.NUMBER, value: 11 },
    { colour: Colour.BLUE, type: Type.NUMBER, value: 12 },
    { colour: Colour.BLUE, type: Type.NUMBER, value: 13 },

    { colour: Colour.RED, type: Type.NUMBER, value: 1 },
    { colour: Colour.RED, type: Type.NUMBER, value: 2 },
    { colour: Colour.RED, type: Type.NUMBER, value: 3 },
    { colour: Colour.RED, type: Type.NUMBER, value: 4 },
    { colour: Colour.RED, type: Type.NUMBER, value: 5 },
    { colour: Colour.RED, type: Type.NUMBER, value: 6 },
    { colour: Colour.RED, type: Type.NUMBER, value: 7 },
    { colour: Colour.RED, type: Type.NUMBER, value: 8 },
    { colour: Colour.RED, type: Type.NUMBER, value: 9 },
    { colour: Colour.RED, type: Type.NUMBER, value: 10 },
    { colour: Colour.RED, type: Type.NUMBER, value: 11 },
    { colour: Colour.RED, type: Type.NUMBER, value: 12 },
    { colour: Colour.RED, type: Type.NUMBER, value: 13 },
]